
# Created on Fri Nov 10 14:08:00 2024
# Copyright (C) 2024-present {nicolas.blanc} @ HEIG-VD
# This file is licensed under the GPL-3.0-only. See LICENSE file for details.
# Third-party libraries and their licenses are listed in the NOTICE.md file.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
      args:
        - --markdown-linebreak-ext=.md
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: detect-private-key
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: check-ast
    - id: debug-statements
    - id: check-yaml
    - id: check-json

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.4
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format

# Sort imports
- repo: https://github.com/pycqa/isort
  rev: '6.0.0'
  hooks:
    - id: isort
      args:
        - --profile=black

- repo: https://github.com/PyCQA/bandit
  rev: '1.8.2'
  hooks:
  - id: bandit
    name: bandit
    args: ["-r", "."] # Recursively check the entire repository
